<a href="https://colab.research.google.com/github/Brafamous/New/blob/main/Synchronous_Machine_Prediction_Using_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Polynomial Regression

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('Synchronous  Machines.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

## Splitting the data set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state =0)

# The Polynomial Regression Model
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

# Predicting the Result
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision =2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))


# Evaluating the Model Performance
from sklearn.metrics import r2_score
performance1=r2_score(y_test, y_pred)

[[434.16 431.23]
 [457.96 460.01]
 [460.65 461.14]
 ...
 [435.23 426.86]
 [436.56 433.4 ]
 [438.67 441.94]]


Decsion Tree Regression

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the dataset
data = pd.read_csv('Synchronous  Machines.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

#Splitting the Data set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state =0)

#Decision Tree model
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

#Predicting the Test Results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision =2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

# Evaluating the Model Performance
from sklearn.metrics import r2_score
performance2=r2_score(y_test, y_pred)

[[432.98 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [428.72 426.86]
 [435.9  433.4 ]
 [443.54 441.94]]


Random Forest Regression

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the #Importing the dataset
data = pd.read_csv('Synchronous  Machines.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

#Splitting the data set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

#Random Forest Model
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators =20, random_state=0)
regressor.fit(X_train,y_train)

#Prediction
y_pred = regressor.predict(X_test)

np.set_printoptions(precision =2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

# Evaluating the Model Performance
from sklearn.metrics import r2_score
performance3=r2_score(y_test, y_pred)


[[434.16 431.23]
 [457.67 460.01]
 [463.44 461.14]
 ...
 [431.92 426.86]
 [436.07 433.4 ]
 [440.98 441.94]]


In [38]:
performance = [performance1, performance2, performance3]
max_performance = max(performance)
print('The best module has a performance of', max_performance)


The best module has a performance of 0.9598466027827742
0.9598466027827742
